AWSTemplateFormatVersion: '2010-09-09'
Transform:                AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime:              nodejs8.10
  Api:
    Cors:
      AllowMethods:       "'POST,OPTIONS'"
      AllowOrigin:        "'*'"
Resources:
  MailmeFunction:
    Type:                 AWS::Serverless::Function
    Properties:
      CodeUri:            dist/
      Handler:            main.handler
      Policies:
        - SESCrudPolicy:
            IdentityName: 'orca-solution.com'
        - Version:        '2012-10-17'
          Statement:
            - Effect:     Allow
              Action:
                - ses:sendTemplatedEmail
              Resource:   '*'
      Events:
        MailmeApi:
          Type:           Api
          Properties:
            Path:         /{template}
            Method:       POST
